INSERT INTO ACCOUNT (NAME) VALUES ('ScottSmith');
INSERT INTO ACCOUNT (NAME) VALUES ('JackWilliam');
INSERT INTO ACCOUNT (NAME) VALUES ('Rose');
INSERT INTO ACCOUNT (NAME) VALUES ('SomeName');
INSERT INTO ACCOUNT (NAME) VALUES ('Tester');